runtime: java11
service: fridger-backend
entrypoint: java -jar fridger-recipes-0.0.1-SNAPSHOT.jar
env: standard
runtime_config:
  jdk: openjdk11

handlers:
- url: /.*
  script: this field is required, but ignored
manual_scaling:
  instances: 1